source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CameraLevel_Example', :exclusive => true do
  pod 'CameraLevel', :path => '../'
end

target 'CameraLevel_Tests', :exclusive => true do
  pod 'CameraLevel', :path => '../'

  
end
